# @package _global_

defaults:
  - train
  - override /task: libero_omnigen2_imagewam
  - _self_

ckpt: null
gpu_id: 0
model_overrides: null
model_overrides_path: null

model:
  load_text_encoder: true
  action_dit_pretrained_path: null

EVALUATION:
  task_suite_name: libero_spatial
  task_id: 0
  task_chunk_file: null
  num_trials: 50
  output_dir: ./evaluate_results/libero_omnigen2/${hydra:runtime.choices.task}/${now:%Y%m%d_%H%M%S}

  env_num: 1
  num_steps_wait: 30
  replan_steps: 10
  binarize_gripper: true
  use_action_ensembler: false
  visualize_future_video: false

  action_horizon: null
  tau_star: 0.0
  num_inference_steps: ${eval_num_inference_steps}
  sigma_shift: null
  text_cfg_scale: 1.0
  negative_prompt: ""
  rand_device: cpu
  tiled: false

  dataset_stats_path: null
  device: cuda

MULTIRUN:
  create_only: false
  task_file: null
  task_suite_names:
    - libero_10
    - libero_goal
    - libero_spatial
    - libero_object
  num_gpus: 8
  gpu_ids: null
  max_tasks_per_gpu: 2
  chunk_size: 1
  task_sample_ratio: null
  task_sample_seed: 42

hydra:
  job:
    chdir: false
  run:
    dir: .
  output_subdir: null
